clear functions
folder = fileparts(which('laca.vlm.gen_VLM_C'));
panels = coder.typeof(0,[4,inf],[0 1]); 
nodes = coder.typeof(0,[3,inf],[0 1]);
AIC = coder.typeof(0,[inf,inf],[1 1]);
V = coder.typeof(0,[3,inf],[0 1]);
te_idx = coder.typeof(0,[inf,2],[1 0]);
gamma = coder.typeof(0,[inf,1],[1 0]);
isTE = coder.typeof(true,[inf 1],[1 0]);
fil_idx = coder.typeof(true,[inf inf],[1 1]);

cfg = coder.config('mex');
cfg.TargetLang = 'C++';
cfg.InlineBetweenUserFunctions = 'Readability';
cfg.EnableAutoParallelization = 1;
cfg.IntegrityChecks = false;
cfg.ResponsivenessChecks = false;
%  cfg.DynamicMemoryAllocation = 'off';

vars = {'-o' fullfile(folder,'vlm_C_code') '-d' fullfile(folder,'codegen','mex','vlm_C_code')...
    '-config' 'cfg' '-report'};
vars = [vars(:)' {which('laca.vlm.vortex_line')} {'-args'} ...
    {{[0;0;0],[0;0;0],[0;0;0],1,1}}];
vars = [vars(:)' {which('laca.vlm.vortex_ring')} {'-args'} ...
    {{zeros(3,4),[0;0;0],1}}];
vars = [vars(:)' {which('laca.vlm.vortex_ring_split')} {'-args'} ...
    {{zeros(3,4),[0;0;0],1}}];
vars = [vars(:)' {which('laca.vlm.horseshoe')} {'-args'} ...
    {{zeros(3,4),[0;0;0],1}}];
vars = [vars(:)' {which('laca.vlm.get_gamma')} {'-args'} ...
    {{nodes,nodes,gamma,AIC}}];
vars = [vars(:)' {which('laca.vlm.panel_normal')} {'-args'} ...
    {{panels,nodes}}];
vars = [vars(:)' {which('laca.vlm.panel_area')} {'-args'} ...
    {{panels,nodes}}];
vars = [vars(:)' {which('laca.vlm.panel_centroid')} {'-args'} ...
    {{panels,nodes}}];
vars = [vars(:)' {which('laca.vlm.get_collocation')} {'-args'} ...
    {{panels,nodes,gamma}}];
vars = [vars(:)' {which('laca.vlm.induced_velocity')} {'-args'} ...
    {{nodes,panels,nodes,panels,nodes,te_idx,gamma}}];
vars = [vars(:)' {which('laca.vlm.apply_result')} {'-args'} ...
    {{nodes,V,nodes,gamma,1}}];
vars = [vars(:)' {which('laca.vlm.get_perimeter_filiments')} {'-args'} ...
    {{panels,nodes,1,isTE}}];
vars = [vars(:)' {which('laca.vlm.generate_rings')} {'-args'} ...
    {{panels,nodes}}];
vars = [vars(:)' {which('laca.vlm.generate_te_horseshoe')} {'-args'} ...
    {{panels,nodes,isTE,[0;0;0]}}];
vars = [vars(:)' {which('laca.vlm.get_moment')} {'-args'} ...
    {{nodes,nodes,[0;0;0]}}];
vars = [vars(:)' {which('laca.vlm.generate_AIC')} {'-args'} ...
    {{panels,nodes,nodes,panels,nodes,te_idx}}];
vars = [vars(:)' {which('laca.vlm.generate_AIC3D')} {'-args'} ...
    {{panels,nodes,nodes,panels,nodes,te_idx}}];
vars = [vars(:)' {which('laca.vlm.filiment_force')} {'-args'} ...
    {{panels,nodes,V,gamma,isTE,1}}];
vars = [vars(:)' {which('laca.vlm.ring_force')} {'-args'} ...
    {{panels,nodes,fil_idx,V,gamma,isTE,1}}];
vars = [vars(:)' {which('laca.vlm.panel_compass')} {'-args'} ...
    {{panels,nodes}}];
tic;
codegen(vars{:})
toc;