function [panels,maxID] = get_panels(obj,ID,varargin)
%GET_PANELS Summary of this function goes here
%   Detailed explanation goes here
    p = inputParser;
    p.addRequired('ID');
    p.addParameter('Density',0.02);
    p.addParameter('IGID',999);
    p.addParameter('Location','none');
    p.parse(ID,varargin{:})

panels(1) = laca.fe.Panel(obj.LE(:,1),obj.LE(:,2),...
    obj.Chord1*(1-obj.ControlRefChord(1)),...
    obj.Chord2*(1-obj.ControlRefChord(2)),...
    'Density',p.Results.Density,'ID',ID,...
    'SplineSet',obj.SplineSet,'IGID',p.Results.IGID,...
    'Location',p.Results.Location,...
    'Normalwash',obj.Normalwash);
if obj.hasControlSurf
    ID = panels(1).MaxID + 1;
    coords = obj.get_panel_coords;
    panels(2) = laca.fe.ControlPanel(...
        coords(2,:,2)',coords(3,:,2)',...
        obj.Chord1*(obj.ControlRefChord(1)),...
        obj.Chord2*(obj.ControlRefChord(2)),...
        'Density',p.Results.Density,'ID',ID,...
        'SplineSet',obj.SplineSet,'IGID',p.Results.IGID,...
        'Location',p.Results.Location,...
        'Name',obj.ControlName,...
        'Normalwash',obj.Normalwash);
end
maxID = panels(end).MaxID + 1;
end

